//@codekit-prepend "../bower_components/jquery/dist/jquery.js"
//@codekit-prepend "../bower_components/fullpage.js/dist/jquery.fullpage.js"
//@codekit-append "components/_slides.js"
//@codekit-append "components/_menu.js"
//@codekit-append "components/_pages.js"