//@codekit-prepend "../bower_components/jquery/jquery.js"
//@codekit-append "../bower_components/jquery-backstretch/jquery.backstretch.js"
//@codekit-append "components/_slides.js"
//@codekit-append "components/_menu.js"
//@codekit-append "components/_pages.js"
